### ISSUE TITLE
Is it going to be published to maven central?

### ISSUE THREAD

**Issue by marlonbernardes** [dsyer/spring-boot-mustache#1]
@dsyer This is the only dependency that I use on my project which is not (apparently) published to maven's central repo. Is it going to be published there or in any other public repository?

**Comment by dsyer** [comment]
I wasn't aware anyone was using it. We can put it in Spring Boot maybe?

**Comment by marlonbernardes** [comment]
@dsyer Yes, that would be great! I'd be glad to help in any way I could.

**Comment by mnrasul** [comment]
yeah, it would be great if it were published, spring boot would be fantastic

**Comment by dsyer** [comment]
Please open an issue at https://github.com/spring-projects/spring-boot/issues

**Comment by mnrasul** [comment]
Did so : https://github.com/spring-projects/spring-boot/issues/2242

Thanks a bunch.
